### ISSUE TITLE
Save-MSCatalogUpdate - Unable to download anything

### ISSUE THREAD

**Issue by jyonke** [ryan-jan/MSCatalog#14]
## Expected Behavior
Files should be downloaded or produce a message indicating that they could not be found.

## Current Behavior
If zero links are found it by default assumes multiple files are available, but no links have actually been found.

## Possible Solution
Microsoft changed the base URL for there update files. RegEx needs to be updated to accommodate and add some simple logic to return a warning if no links are found, 

## Steps to Reproduce
1. Install latest version of MSCatlog Module from PSGallery
2. Run example snippet from ReadMe - Save-MSCatalogUpdate -Guid "4734d13d-5e5a-4b64-9e93-225674ec811c" -Destination ".\"

![image](https://user-images.githubusercontent.com/19600775/161388335-ca5b3264-740e-44cc-bb08-406ca2747cbb.png)

**Comment by xxbiohazrdxx** [comment]
Fixed by #16
