### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by xxbiohazrdxx** [ryan-jan/MSCatalog#18]
Are you looking for someone to take over this package? Wondering since there havent been any merges in a while

**Comment by ryan-jan** [comment]
Hi, yes I would be open to that, or you can clone the project and I can archive this one? I no longer use this as I changed roles back in Sept last year so I just can't commit time to keeping it up to date.

**Comment by xxbiohazrdxx** [comment]
I'd be down to take over, if you want to transfer. A fork would work as well, but ideally I'd like to keep continuity with the PS Gallery releases.

**Comment by ryan-jan** [comment]
I've invited you to be a collaborator on this repo for the time being. I think this is the easiest way to start with, what do you think?

**Comment by xxbiohazrdxx** [comment]
Awesome, works for me. Thanks!
