### ISSUE TITLE
-strict paramter stopped working

### ISSUE THREAD

**Issue by ITSNOTSTUPIDIFITWORKS** [ryan-jan/MSCatalog#26]
Get-MSCatalogUpdate -Search $searchstring -SortBy LastUpdated -Descending -IncludeFileNames -Strict

```
Exception: C:\Program Files\PowerShell\Modules\MSCatalog\0.27.0\Public\Get-MSCatalogUpdate.ps1:106
Line |
 106 |  …             $_.SelectNodes("td")[1].innerText.Trim() -like "*$Search* …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

**Comment by ITSNOTSTUPIDIFITWORKS** [comment]
Fix: 
add `$_.Id -ne "headerRow" -and` in Get-MSCatalogUpdate.ps1

`$_.Id -ne "headerRow" -and
                $_.SelectNodes("td")[1].innerText.Trim() -like "*$Search*"`

**Comment by RJohnsonPGH** [comment]
Are you using the latest version from here, or the PSGallery? This should have been fixed by https://github.com/ryan-jan/MSCatalog/commit/003a30587f245076f83d25374710a47a613cfe54 but that has not been pushed to the gallery yet.

**Comment by ITSNOTSTUPIDIFITWORKS** [comment]
Oh i see. Thank you. Used the PSGallery version.
