### ISSUE TITLE
Script is unable to determine url for "Servicing Stack Updates"

### ISSUE THREAD

**Issue by kilianmeister** [ryan-jan/MSCatalog#3]
Microsoft changed the URL from http://download.windowsupdate.com to http://dl.delivery.mp.microsoft.com. Therfore a download is not eaven possible.

**Comment by ryan-jan** [comment]
I had not realised this yet. I will patch this ASAP. Thanks for spotting this and raising the issue.

**Comment by ryan-jan** [comment]
@kilianmeister I have just pushed a fixed version 0.19.0 to the PowerShell Gallery. I would really appreciate if you could test it out and let me know if it has resolved your issue?

**Comment by ryan-jan** [comment]
Closing as issue resolved in #108657d
