### ISSUE TITLE
System and PS requirements to use MSCatalog

### ISSUE THREAD

**Issue by komsorg** [ryan-jan/MSCatalog#4]
Please, add System and PowerShell requirements section to readme.md for using MSCatalog.

**Comment by ryan-jan** [comment]
Sure, this is a valid suggestion.

**Comment by ryan-jan** [comment]
I have now added an OS/PS version matrix to the README.

**Comment by komsorg** [comment]
You forgot to mention NuGet dependency.

**Comment by ryan-jan** [comment]
There is no dependency on NuGet. Please explain?
